name: Update feeds (default + realtors)

on:
  schedule:
    - cron: "0 * * * *"   # elke uur (UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-feeds
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Bepaal realtor IDs
        id: ids
        shell: bash
        run: |
          set -e
          if [ -f .github/realtors.txt ]; then
            IDS=$(grep -E '^[a-f0-9-]{36}$' .github/realtors.txt | tr -d '' | tr '
' ' ' | xargs || true)
          else
            IDS="79013c6a-1a81-40b2-9f89-3e7d0354a4f8 b0d5bb0f-a144-43e7-a6d9-112cd4c8c87b"
          fi
          echo "ids=${IDS}" >> $GITHUB_OUTPUT
          echo "IDs: ${IDS}"

      - name: Maak data-map
        run: mkdir -p data

      - name: Haal algemene feed op
        id: defaultfeed
        shell: bash
        continue-on-error: true
        run: |
          set -e
          TMP=$(mktemp)
          if curl -fsSL "https://venapp.accept.paqt.io/feed" -H "Accept: application/json" -o "${TMP}"; then
            mv "${TMP}" "data/feed.json"
            echo "ok=true" >> $GITHUB_OUTPUT
          else
            echo "WAARSCHUWING: algemene feed kon niet opgehaald worden" >&2
            echo "ok=false" >> $GITHUB_OUTPUT
          fi

      - name: Haal makelaarsfeeds op
        id: realtorfeeds
        shell: bash
        continue-on-error: true
        run: |
          set -e
          CHANGED=0
          OKCOUNT=0
          for ID in ${{ steps.ids.outputs.ids }}; do
            [ -n "$ID" ] || continue
            URL="https://venapp.accept.paqt.io/realtor/${ID}/feed"
            TARGET="data/realtor-${ID}.json"
            TMP=$(mktemp)
            if curl -fsSL "${URL}" -H "Accept: application/json" -o "${TMP}"; then
              OKCOUNT=$((OKCOUNT+1))
              if [ -f "${TARGET}" ] && cmp -s "${TMP}" "${TARGET}"; then
                echo "Geen wijziging voor ${TARGET}"
                rm -f "${TMP}"
                continue
              fi
              mv "${TMP}" "${TARGET}"
              echo "Geüpdatet: ${TARGET}"
              CHANGED=1
            else
              echo "WAARSCHUWING: kon ${URL} niet ophalen" >&2
            fi
          done
          echo "changed=${CHANGED}" >> $GITHUB_OUTPUT
          echo "okcount=${OKCOUNT}" >> $GITHUB_OUTPUT

      - name: Schrijf ALTIJD index.json (ook als er geen feeds zijn)
        shell: bash
        run: |
          NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          DEFAULT=""
          if [ -f data/feed.json ]; then DEFAULT="data/feed.json"; fi
          # Verzamel bestaande realtor-bestanden
          FILES=()
          for f in data/realtor-*.json; do
            [ -e "$f" ] || continue
            FILES+=("$f")
          done
          # Schrijf index.json
          {
            echo '{'
            echo '  "generated_at": "'${NOW}'",'
            echo '  "default_feed": '$( [ -n "$DEFAULT" ] && printf '"%s"' "$DEFAULT" || printf 'null' )','
            echo '  "realtor_files": ['
            for i in "${!FILES[@]}"; do
              if [ $i -gt 0 ]; then echo ','; fi
              printf '    "%s"' "${FILES[$i]}"
            done
            echo ''
            echo '  ]'
            echo '}'
          } > data/index.json

      - name: Commit & push wijzigingen (data/*.json en index.json)
        shell: bash
        run: |
          set -e
          if [[ -n "$(git status --porcelain data/)" ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add data/*.json
            git commit -m "Update feeds + index.json [skip ci]"
            git push
          else
            echo "Geen wijzigingen om te committen"
          fi
