name: Update feed.json

on:
  schedule:
    - cron: "0 * * * *"   # 1× per uur
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch default feed
        run: |
          mkdir -p data
          curl -sSL https://venapp.accept.paqt.io/feed \
            -H "Accept: application/json" \
            -o data/feed.json

      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain data/feed.json)" ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add data/feed.json
            git commit -m "Update feed.json [skip ci]"
            git push
          else
            echo "No changes in feed.json"
          fi
